-- Schema "core" canonico (PostgreSQL). Porte de scripts/migration/001_create_core_schema.sql.
-- Convencoes: ids BIGINT IDENTITY (BY DEFAULT permite preservar ids legados no ETL),
-- timestamps TIMESTAMPTZ default now(), flags BOOLEAN, soft-delete via deleted_at.

CREATE TABLE ops_migration_runs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_key VARCHAR(120) NOT NULL,
  started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at   TIMESTAMPTZ NULL,
  run_status    VARCHAR(20) NOT NULL,
  details       TEXT NULL
);
CREATE INDEX idx_ops_migration_runs_started_at ON ops_migration_runs (started_at);
CREATE INDEX idx_ops_migration_runs_status ON ops_migration_runs (run_status);

CREATE TABLE app_admin_users (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_admin_id    BIGINT NULL,
  username           VARCHAR(120) NOT NULL,
  password_hash      VARCHAR(255) NOT NULL,
  password_algorithm VARCHAR(20) NOT NULL DEFAULT 'MD5',
  is_active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_by         BIGINT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by         BIGINT NULL,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by         BIGINT NULL,
  deleted_at         TIMESTAMPTZ NULL,
  CONSTRAINT uk_app_admin_users_username UNIQUE (username),
  CONSTRAINT uk_app_admin_users_legacy_admin_id UNIQUE (legacy_admin_id)
);
CREATE INDEX idx_app_admin_users_deleted_at ON app_admin_users (deleted_at);

CREATE TABLE app_users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_user_id BIGINT NULL,
  display_name   VARCHAR(150) NOT NULL,
  email          VARCHAR(190) NOT NULL,
  phone          VARCHAR(40) NULL,
  password_hash  VARCHAR(255) NULL,
  user_type      VARCHAR(30) NOT NULL DEFAULT 'Normal',
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  avatar_ref     VARCHAR(255) NULL,
  acervo_id      BIGINT NULL,
  created_by     BIGINT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by     BIGINT NULL,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by     BIGINT NULL,
  deleted_at     TIMESTAMPTZ NULL,
  CONSTRAINT uk_app_users_email UNIQUE (email),
  CONSTRAINT uk_app_users_legacy_user_id UNIQUE (legacy_user_id)
);
CREATE INDEX idx_app_users_is_active ON app_users (is_active);
CREATE INDEX idx_app_users_acervo_id ON app_users (acervo_id);
CREATE INDEX idx_app_users_deleted_at ON app_users (deleted_at);

CREATE TABLE app_user_identities (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  provider         VARCHAR(30) NOT NULL,
  provider_user_id VARCHAR(190) NOT NULL,
  created_by       BIGINT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by       BIGINT NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by       BIGINT NULL,
  deleted_at       TIMESTAMPTZ NULL,
  CONSTRAINT uk_app_user_identities_provider_uid UNIQUE (provider, provider_user_id),
  CONSTRAINT fk_app_user_identities_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);
CREATE INDEX idx_app_user_identities_user ON app_user_identities (user_id);
CREATE INDEX idx_app_user_identities_deleted_at ON app_user_identities (deleted_at);

CREATE TABLE catalog_categories (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_category_id BIGINT NULL,
  category_type      VARCHAR(20) NOT NULL DEFAULT 'BOOK',
  name               VARCHAR(120) NOT NULL,
  slug               VARCHAR(140) NOT NULL,
  is_active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_by         BIGINT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by         BIGINT NULL,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by         BIGINT NULL,
  deleted_at         TIMESTAMPTZ NULL,
  CONSTRAINT uk_catalog_categories_type_slug UNIQUE (category_type, slug),
  CONSTRAINT uk_catalog_categories_legacy_id UNIQUE (legacy_category_id)
);
CREATE INDEX idx_catalog_categories_type_status ON catalog_categories (category_type, is_active);
CREATE INDEX idx_catalog_categories_deleted_at ON catalog_categories (deleted_at);

CREATE TABLE catalog_authors (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_author_id BIGINT NULL,
  author_type      VARCHAR(20) NOT NULL DEFAULT 'BOOK',
  name             VARCHAR(150) NOT NULL,
  bio              TEXT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_by       BIGINT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by       BIGINT NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by       BIGINT NULL,
  deleted_at       TIMESTAMPTZ NULL,
  CONSTRAINT uk_catalog_authors_legacy_id UNIQUE (legacy_author_id)
);
CREATE INDEX idx_catalog_authors_type_status ON catalog_authors (author_type, is_active);
CREATE INDEX idx_catalog_authors_name ON catalog_authors (name);
CREATE INDEX idx_catalog_authors_deleted_at ON catalog_authors (deleted_at);

CREATE TABLE catalog_books (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_book_id   BIGINT NULL,
  title            VARCHAR(255) NOT NULL,
  normalized_title VARCHAR(255) NOT NULL,
  category_id      BIGINT NULL,
  author_id        BIGINT NULL,
  description      TEXT NULL,
  file_type        VARCHAR(100) NULL,
  file_url         TEXT NULL,
  is_featured      BOOLEAN NOT NULL DEFAULT FALSE,
  views            INTEGER NOT NULL DEFAULT 0,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_by       BIGINT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by       BIGINT NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by       BIGINT NULL,
  deleted_at       TIMESTAMPTZ NULL,
  CONSTRAINT uk_catalog_books_legacy_id UNIQUE (legacy_book_id),
  CONSTRAINT fk_catalog_books_category FOREIGN KEY (category_id) REFERENCES catalog_categories (id) ON DELETE SET NULL,
  CONSTRAINT fk_catalog_books_author FOREIGN KEY (author_id) REFERENCES catalog_authors (id) ON DELETE SET NULL
);
CREATE INDEX idx_catalog_books_is_active ON catalog_books (is_active);
CREATE INDEX idx_catalog_books_title ON catalog_books (normalized_title);
CREATE INDEX idx_catalog_books_category ON catalog_books (category_id);
CREATE INDEX idx_catalog_books_author ON catalog_books (author_id);
CREATE INDEX idx_catalog_books_deleted_at ON catalog_books (deleted_at);

CREATE TABLE engagement_comments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_comment_id  BIGINT NULL,
  book_id            BIGINT NOT NULL,
  user_id            BIGINT NULL,
  user_name          VARCHAR(150) NULL,
  user_email         VARCHAR(190) NULL,
  comment_text       TEXT NOT NULL,
  commented_at_epoch BIGINT NULL,
  is_active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_by         BIGINT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by         BIGINT NULL,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by         BIGINT NULL,
  deleted_at         TIMESTAMPTZ NULL,
  CONSTRAINT uk_engagement_comments_legacy_id UNIQUE (legacy_comment_id),
  CONSTRAINT fk_engagement_comments_book FOREIGN KEY (book_id) REFERENCES catalog_books (id) ON DELETE CASCADE,
  CONSTRAINT fk_engagement_comments_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE SET NULL
);
CREATE INDEX idx_engagement_comments_book ON engagement_comments (book_id);
CREATE INDEX idx_engagement_comments_user ON engagement_comments (user_id);
CREATE INDEX idx_engagement_comments_is_active ON engagement_comments (is_active);
CREATE INDEX idx_engagement_comments_deleted_at ON engagement_comments (deleted_at);

CREATE TABLE app_settings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key   VARCHAR(120) NOT NULL,
  setting_value TEXT NOT NULL,
  setting_group VARCHAR(60) NOT NULL DEFAULT 'GENERAL',
  created_by    BIGINT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by    BIGINT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by    BIGINT NULL,
  deleted_at    TIMESTAMPTZ NULL,
  CONSTRAINT uk_app_settings_key UNIQUE (setting_key)
);
CREATE INDEX idx_app_settings_group ON app_settings (setting_group);
CREATE INDEX idx_app_settings_deleted_at ON app_settings (deleted_at);

CREATE TABLE app_user_activity_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_log_id BIGINT NULL,
  user_id       BIGINT NOT NULL,
  player_id     VARCHAR(255) NULL,
  created_by    BIGINT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by    BIGINT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by    BIGINT NULL,
  deleted_at    TIMESTAMPTZ NULL,
  CONSTRAINT uk_app_user_activity_logs_legacy_id UNIQUE (legacy_log_id),
  CONSTRAINT uk_app_user_activity_logs_user UNIQUE (user_id),
  CONSTRAINT fk_app_user_activity_logs_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);
CREATE INDEX idx_app_user_activity_logs_deleted_at ON app_user_activity_logs (deleted_at);

-- Equivalente ao ON UPDATE CURRENT_TIMESTAMP do MySQL: mantem updated_at sincronizado.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_app_admin_users_updated_at BEFORE UPDATE ON app_admin_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_app_users_updated_at BEFORE UPDATE ON app_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_app_user_identities_updated_at BEFORE UPDATE ON app_user_identities FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_catalog_categories_updated_at BEFORE UPDATE ON catalog_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_catalog_authors_updated_at BEFORE UPDATE ON catalog_authors FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_catalog_books_updated_at BEFORE UPDATE ON catalog_books FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_engagement_comments_updated_at BEFORE UPDATE ON engagement_comments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_app_settings_updated_at BEFORE UPDATE ON app_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_app_user_activity_logs_updated_at BEFORE UPDATE ON app_user_activity_logs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
